using Microsoft.Extensions.Localization;

namespace GangsAPI;

public enum MSG {
  COMMAND_GANG_NOTINGANG,
  COMMAND_GANG_CREATE_ALREADY_EXISTS,
  COMMAND_GANG_CREATE_SUCCESS,
  COMMAND_INVITE_NONE,
  COMMAND_INVITE_MAXINVITES,
  COMMAND_INVITE_ALREADY_INVITED,
  COMMAND_INVITE_ALREADY_IN_GANG,
  COMMAND_INVITE_IN_YOUR_GANG,
  COMMAND_INVITE_SUCCESS,
  GENERIC_STEAM_NOT_FOUND,
  COMMAND_BALANCE_NONE,
  COMMAND_BALANCE,
  COMMAND_BALANCE_GANG,
  COMMAND_BALANCE_GANG_NONE,
  COMMAND_BALANCE_OTHER_NONE,
  COMMAND_BALANCE_OTHER,
  COMMAND_BALANCE_SET,
  COMMAND_GANG_DISBAND_WARN,
  COMMAND_GANG_DISBANDED,
  COMMAND_USAGE,
  COMMAND_INVALID_PARAM,
  PREFIX,
  GENERIC_PLAYER_NOT_FOUND,
  GENERIC_PLAYER_FOUND_MULTIPLE,
  SOONTM,
  GENERIC_PLAYER_ONLY,
  GENERIC_NOPERM,
  GENERIC_NOPERM_NODE,
  GENERIC_NOPERM_RANK,
  GENERIC_ERROR,
  GENERIC_ERROR_INFO,
  CURRENCY,
  GANG_NOT_FOUND,
  GANG_NOT_FOUND_CLOSEST,
  COLOR_DEFAULT,
  COLOR_EMPHASIS,
  COLOR_NUMBERL,
  COLOR_SPECIAL,
  COLOR_COMMAND,
  COLOR_CURRENCY,
  COLOR_TARGET,
  COLOR_GANG,
  ALREADY_IN_GANG,
  NOT_IN_GANG,
  PERK_MISSING,
  PERK_PURCHASED,
  PERK_UNPURCHASABLE,
  PERK_UNPURCHASABLE_WITH_ITEM,
  PERK_NOT_FOUND,
  PERK_MOTD_SET,
  GANG_CHAT_FORMAT,
  ECO_INSUFFICIENT_FUNDS,
  ECO_INSUFFICIENT_FUNDS_WITH_ITEM,
  ECO_PURCHASED,
  ECO_PURCHASED_WITHITEM,
  ECO_PURCHASED_WITHGANG,
  ECO_PURCHASED_WITHGANG_ITEM,
  ECO_PURCHASED_WITHBOTH,
  ECO_PURCHASED_WITHBOTH_ITEM,
  ECO_PLAYER_GIVE_NEGATIVE,
  ECO_PLAYER_GIVE_POSITIVE,
  ECO_GANG_GIVE_NEGATIVE,
  ECO_GANG_GIVE_POSITIVE
}

public static class LocaleExtensions {
  public static string Key(this MSG msg) {
    return msg switch {
      MSG.COMMAND_GANG_NOTINGANG => "command.gang.not_in_gang",
      MSG.COMMAND_GANG_CREATE_ALREADY_EXISTS =>
        "command.gang.create.already_exists",
      MSG.COMMAND_GANG_CREATE_SUCCESS => "command.gang.create.success",
      MSG.COMMAND_INVITE_NONE         => "command.gang.invite.none",
      MSG.COMMAND_INVITE_MAXINVITES   => "command.gang.invite.max_invites",
      MSG.COMMAND_INVITE_ALREADY_INVITED =>
        "command.gang.invite.already_invited",
      MSG.COMMAND_INVITE_ALREADY_IN_GANG =>
        "command.gang.invite.already_ingang",
      MSG.COMMAND_INVITE_IN_YOUR_GANG =>
        "command.gang.invite.already_inyourgang",
      MSG.COMMAND_INVITE_SUCCESS        => "command.gang.invite.success",
      MSG.COMMAND_BALANCE_NONE          => "command.balance.none",
      MSG.COMMAND_BALANCE               => "command.balance",
      MSG.COMMAND_BALANCE_OTHER         => "command.balance.other",
      MSG.COMMAND_BALANCE_OTHER_NONE    => "command.balance.other.none",
      MSG.COMMAND_BALANCE_SET           => "command.balance.set",
      MSG.COMMAND_BALANCE_GANG          => "command.balance.gang",
      MSG.COMMAND_BALANCE_GANG_NONE     => "command.balance.gang.none",
      MSG.COMMAND_USAGE                 => "command.usage",
      MSG.COMMAND_INVALID_PARAM         => "command.invalid_parameter",
      MSG.COMMAND_GANG_DISBAND_WARN     => "command.gang.disband.warning",
      MSG.COMMAND_GANG_DISBANDED        => "command.gang.disbanded",
      MSG.PREFIX                        => "prefix",
      MSG.GENERIC_PLAYER_NOT_FOUND      => "generic.player.not_found",
      MSG.SOONTM                        => "generic.soontm",
      MSG.GENERIC_PLAYER_ONLY           => "generic.player.only",
      MSG.GENERIC_STEAM_NOT_FOUND       => "generic.player.steam_not_found",
      MSG.GENERIC_NOPERM                => "generic.no_permission",
      MSG.GENERIC_NOPERM_NODE           => "generic.no_permission.node",
      MSG.GENERIC_NOPERM_RANK           => "generic.no_permission.rank",
      MSG.GENERIC_PLAYER_FOUND_MULTIPLE => "generic.player.found_multiple",
      MSG.GENERIC_ERROR                 => "generic.error",
      MSG.GENERIC_ERROR_INFO            => "generic.error.info",
      MSG.CURRENCY                      => "currency",
      MSG.COLOR_DEFAULT                 => "color.default",
      MSG.COLOR_EMPHASIS                => "color.emph",
      MSG.COLOR_NUMBERL                 => "color.number",
      MSG.COLOR_SPECIAL                 => "color.special",
      MSG.COLOR_COMMAND                 => "color.command",
      MSG.COLOR_CURRENCY                => "color.currency",
      MSG.COLOR_TARGET                  => "color.target",
      MSG.COLOR_GANG                    => "color.gang",
      MSG.ALREADY_IN_GANG               => "gang.already_in_gang",
      MSG.NOT_IN_GANG                   => "gang.not_in_gang",
      MSG.PERK_MISSING                  => "perk.missing",
      MSG.PERK_PURCHASED                => "perk.purchased",
      MSG.PERK_UNPURCHASABLE            => "perk.unpurchasable",
      MSG.PERK_UNPURCHASABLE_WITH_ITEM  => "perk.unpurchasable_withitem",
      MSG.PERK_NOT_FOUND                => "perk.not_found",
      MSG.PERK_MOTD_SET                 => "perk.motd.set",
      MSG.GANG_CHAT_FORMAT              => "perk.gangchat.format",
      MSG.GANG_NOT_FOUND                => "gang.not_found",
      MSG.GANG_NOT_FOUND_CLOSEST        => "gang.not_found.closest",
      MSG.ECO_INSUFFICIENT_FUNDS        => "eco.insufficient_funds",
      MSG.ECO_INSUFFICIENT_FUNDS_WITH_ITEM =>
        "eco.insufficient_funds.with_item",
      MSG.ECO_PURCHASED => "eco.purchased",
      MSG.ECO_PURCHASED_WITHITEM => "eco.purchased.with_item",
      MSG.ECO_PURCHASED_WITHGANG => "eco.purchased.with_gang",
      MSG.ECO_PURCHASED_WITHGANG_ITEM => "eco.purchased.with_gang.with_item",
      MSG.ECO_PURCHASED_WITHBOTH => "eco.purchased.with_both",
      MSG.ECO_PURCHASED_WITHBOTH_ITEM => "eco.purchased.with_both.with_item",
      MSG.ECO_PLAYER_GIVE_NEGATIVE => "eco.player.granted.negative",
      MSG.ECO_PLAYER_GIVE_POSITIVE => "eco.player.granted.positive",
      MSG.ECO_GANG_GIVE_NEGATIVE => "eco.gang.granted.negative",
      MSG.ECO_GANG_GIVE_POSITIVE => "eco.gang.granted.positive",
      _ => throw new ArgumentOutOfRangeException(nameof(msg), msg, null)
    };
  }

  public static string Get(this IStringLocalizer localizer, MSG msg,
    params object[] args) {
    try { return localizer[msg.Key(), args].Value; } catch (FormatException e) {
      throw new FormatException(
        $"There was an error formatting {msg.Key()} ({localizer[msg.Key()]})",
        e);
    }
  }
}