# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nightlies

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'Gangs*/**'
      - '.github/workflows/nightly.yml'
      - '.github/workflows/release.yml'
      - 'Core/**'
      - 'Commands/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          show-progress: true,

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: |
          dotnet restore
          dotnet build Gangs/Gangs.csproj --no-restore
          dotnet publish Gangs/Gangs.csproj --no-build --no-restore

      - uses: actions/upload-artifact@v4.0.0
        with:
          name: gangs-nightly
          path: build/Gangs
          # If build didn't put any artifacts in the build folder, consider it an error
          if-no-files-found: error
  post_webhook:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: POST Webhook
        run: |
          curl -X POST \
            --fail \
            -F token=${{ secrets.GITLAB_SECRET_TOKEN }} \
            -F ref=dev \
            https://gitlab.edgegamers.io/api/v4/projects/2594/trigger/pipeline
